### ISSUE TITLE
fix mongo fits header information

### ISSUE THREAD

**Issue by lspitler** [AstroHuntsman/huntsman-pocs#12]

**Comment by wtgee** [comment]
I fixed the insert error last night so this should be fixed. Will double-check we have the stored information later today.  The bug was related to the `equinox` item not serializing correctly. The fix is hard-coded for `equinox` but should just be a more robust method of serializing any object. See comment in https://github.com/panoptes/POCS/issues/206

**Comment by wtgee** [comment]
Fixed as part of https://github.com/panoptes/POCS/pull/225
